baseURL: http://iagosaito.com
languageCode: en-us
title: iagosaito.com
theme: "PaperMod"
googleAnalytics: G-75TR585LH3

params:

  homeInfoParams: 
    content: Ninguém lê mais nada hoje em dia, mas eu continuo a escrever mesmo assim. Uns artigos aí principalmente sobre tech, mas tem sobre a vida também. Abraços!
  socialIcons:
    - name: github
      url: https://github.com/iagosaito
    - name: spotify
      url: https://open.spotify.com/user/iagosaito?si=bd12e50a5615400d
    - name: goodreads
      url: https://www.goodreads.com/user/show/164680356-iago-saito

  ShowReadingTime: true
  ShowShareButtons: true
  ShowPostNavLinks: false
  ShowBreadCrumbs: true
  ShowCodeCopyButtons: false
  ShowWordCount: true
  ShowRssButtonInSectionTermList: true
  UseHugoToc: true
  disableSpecial1stPost: false
  disableScrollToTop: false
  comments: false
  hidemeta: false
  hideSummary: false
  showtoc: true
  tocopen: false

markup:
  goldmark:
    renderer:
      unsafe: true

menu:
  main:
    - identifier: categories
      name: Categories
      url: /categories/
      weight: 10
    - identifier: tags
      name: Tags
      url: /tags/
      weight: 20
    - identifier: archive
      name: Archive
      url: /archives/
      weight: 30